### ISSUE TITLE
Add scripts to download and preprocess ground-truth networks for experimental scRNA seq-datasets

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/Beeline#34]
These ground-truth networks are not a part of any of our supplemental materials, including Zenodo. We will add scripts to download and pre-process them.

**Comment by zrq0123** [comment]
Hi, All. If there are some progress about the download and pre-process scripts of the scRNA-seq ground-truth networks ? or if it is possible to provide a link to download them?

**Comment by adyprat** [comment]
@zrq0123 
Hi,
There was a licensing issue in making the network data, which has since been resolved. The networks are now available on the same Zenodo link under a new file "BEELINE-Networks.zip" that can be accessed here: https://zenodo.org/record/3701939. I will add the pre-processing scripts to this GitHub repository in the next couple of days and post an update here. Let me know if you have any difficulty accessing the data.
-Aditya

**Comment by zrq0123** [comment]
@adyprat Thanks very much, it really helps!

**Comment by adyprat** [comment]
Fixed in 83eb494
