### ISSUE TITLE
Duplicated rows on refNetwork.csv

### ISSUE THREAD

**Issue by joseale2310** [Murali-group/Beeline#38]
Hi! 

I am quite interested in the evaluation of different GRN inference models. However, I have a question. What is the point of having duplicated rows in the refNetwork.csv example file? 

For example, the first 3 interactions are duplicated (SOX9 is also autoregulated). Sometimes there are also interactions that appear twice in different order, are the interactions in this file directional and this mean the regulate each other?

Thanks!

**Comment by adyprat** [comment]
Hi,
We normally take the unique rows in the refNetwork.csv file in BLEval. Since duplicated rows represent the same edge, we remove duplicates while computing AUPRC/Early precision, and so on. As for why some of them are duplicated in the refNetwork.csv file: that file was automatically generated after parsing the Boolean rule for each gene/TF in the GSD model, so if a rule for gene A was A:= (B and C) or (B and D) in the model, you might see edges B->A duplicated (the other edges are C-A and D->A).

As for the second question, you are correct in thinking that the edge list represents a *directed network*, so if edge A -> b and B -> a appears in the refNetwork.csv, it just represents a mutual interaction. We also included auto-regulation if it is present in the ground-truth.

Hope that helps.
Best,
Aditya
