### ISSUE TITLE
Not able to run some algorithms

### ISSUE THREAD

**Issue by Zengggg** [Murali-group/Beeline#44]
Hi,
     I have successfully installed all the images, but I have some problems when I run BLRunner.py with 'should_run = [True]' for SCRIBE, GRISLI, SINGE, GRNVBEM, GENIE3 and GRNBOOST2. The problems are presented in the images. I do not know how to solve them. Hope that you can give me some advice. Thank you very much!
Best,
Yanping
![genie3 grnboost2-1](https://user-images.githubusercontent.com/48615640/107033633-8ff5e180-67f0-11eb-983b-99b7c05445c1.png)
![genie3 grnboost2-2](https://user-images.githubusercontent.com/48615640/107033643-92583b80-67f0-11eb-80a7-07834b24272d.png)
![grisli](https://user-images.githubusercontent.com/48615640/107033652-96845900-67f0-11eb-99a2-dad2a77a0af6.png)
![grnvbem](https://user-images.githubusercontent.com/48615640/107033664-997f4980-67f0-11eb-8e93-e5be79d86283.png)
![scribe](https://user-images.githubusercontent.com/48615640/107033666-9ab07680-67f0-11eb-9ee7-ac2a9af6b7a2.png)
![singe-1](https://user-images.githubusercontent.com/48615640/107033674-9be1a380-67f0-11eb-98ab-ab2345226c3d.png)
![singe-2](https://user-images.githubusercontent.com/48615640/107033682-9dab6700-67f0-11eb-9f70-226672e2e6f9.png)

**Comment by tmmurali** [comment]
@Zengggg thank you for this report. Can you cut and paste the text of the command line output rather than attaching screenshots. It will help if you can post the output for one algorithm in each individual reply to this message.

Some of the errors look like permissions issues for a shell script. For example, for SINGE, have you tried changing the permissions for SINGE.sh so that it can be executed? The same goes for GRISLI.

For Scribe, did you get an error with installation of Monocle when you installed BEELINE?

**Comment by Zengggg** [comment]
@tmmurali Can you tell you tell what SINGE.sh exactly is? I look at all files under the dicretory */BLRun/, and singeRunner.py and grisliRunner.py both has a permission 'rw-rw-r--'.

**Comment by adyprat** [comment]
Hi @Zengggg ,

I think the permission issue regarding the other algorithms is because user running the docker is unable to write output to your current folder/ cannot access the time command. I pushed an update for SINGE, GRISLI, GRNVBEM on to the master branch that fixes this issue. Please rebuild your docker files for these algorithms and re-run them. Let me know if you  are still having issues for these three here.

I responded to your message on SCRIBE, Arboreto (GENIE3, GRNBoost2) in the separate issue and we can continue the discussion there.

Best,
Aditya
