### ISSUE TITLE
adding new files 

### ISSUE THREAD

**Issue by xPandasx** [Murali-group/Beeline#55]
Hi, 
I recently downloaded Beeline for my Bachelor thesis and Beeline comes along with example Datasets already which i could calculate.
I wanted to use my own Datasets or from the https://zenodo.org/record/3701939 website.
I wanted to make sure which zip, from the two listed there, i should download and where to implement them or in which files i need to change the exaple datasets with the new ones
Thanks for your help

**Comment by ktakers** [comment]
Thank you for using BEELINE.  Please download and extract the BEELINE-data.zip file under the root directory for BEELINE, which should populate the input and config-files directories with data and configuration for synthetic, curated, and scRNA-seq benchmarks.  The YAML files under config-files can be used instead of config-files/config.yaml to run the benchmarks for each dataset, for example:

`python BLRunner.py --config config-files/Curated/GSD.yaml`

Please refer to the README.txt in BEELINE-data.zip regarding the directory structure and the expected content for each file if you would like to add your own datasets.

The BEELINE-Networks.zip file contains the reference networks for the evaluation of the scRNA-seq datasets, and can be extracted following that directory structure under input.
